#
- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Check is swap enable
  shell: swapon
  register: swap_present
  changed_when: false
  ignore_errors: true

- name: If swap is enabled - disable it
  shell: swapoff -a
  when: swap_present.stdout != ""

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s*swap\s*.*)$'
    replace: '# \1'

- name: Disable SELinux
  selinux:
    state: disabled
  register: selinux_ret

- name: Reboot server after selinux policy changed
  shell: sleep 5 && reboot now
  async: 1
  poll: 0
  when: selinux_ret.reboot_required

- name: Wait untill server rebooted
  wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    delay: 5
    timeout: 60
  delegate_to: 127.0.0.1
  when: selinux_ret.reboot_required
